"""
consensus/consensus_engine.py
------------------------------
Consensus Engine — PhantomClaw v2 multi-agent coordination layer.

PURPOSE
-------
Aggregates AgentVote outputs from four specialist agents into a
single TradeRecommendation using confidence-based voting.

AGENTS AGGREGATED
-----------------
  1. OpenClawAgent      (LLM)
  2. TrendAgent         (Deterministic)
  3. MomentumAgent      (Deterministic)
  4. MeanReversionAgent (Deterministic)

VOTE RESOLUTION
---------------
  BUY_SCORE = sum(confidence of BUY votes)
  SELL_SCORE = sum(confidence of SELL votes)
  HOLD_SCORE = sum(confidence of HOLD votes)

  The signal with the highest score wins.
  If there is a tie, the result is HOLD.

CONFIDENCE THRESHOLD
--------------------
  MIN_CONSENSUS_SCORE = 1.5

  If the maximum score is less than 1.5, the decision is forced to HOLD.

FINAL CONFIDENCE
----------------
  FINAL_CONFIDENCE = sum(confidence²) / sum(confidence)
  computed only from the agents in the winning group.

HOLD
----
  HOLD is a first-class action in TradeRecommendation.
  action="HOLD", quantity=0 is always used directly.
"""

from __future__ import annotations

import logging

from agents.mean_reversion_agent import analyze as mean_reversion_analyze
from agents.momentum_agent import analyze as momentum_analyze
from agents.trend_agent import analyze as trend_analyze
from models.agent_vote_model import AgentVote
from models.trade_model import TradeRecommendation

logger = logging.getLogger(__name__)

# ─── Constants ────────────────────────────────────────────────────────────────

_EXECUTE_QUANTITY:       int   = 10
_HOLD_QUANTITY:          int   = 0
MIN_CONSENSUS_SCORE:   float = 1.5

# ─── Public Interface ─────────────────────────────────────────────────────────


def get_consensus(
    symbol: str,
    openclaw_vote: AgentVote,
    market_snapshot: dict,
    indicators: dict,
) -> TradeRecommendation:
    """
    Run the deterministic specialist agents and aggregate with OpenClaw's vote
    using confidence-based scoring.

    Args:
        symbol:          Ticker symbol (e.g. "AAPL").
        openclaw_vote:   The AgentVote previously generated by OpenClaw.
        market_snapshot: Latest OHLCV snapshot dict.
        indicators:      Computed indicator dict.

    Returns:
        A single TradeRecommendation representing the consensus decision.
        action="HOLD" with quantity=0 means no order should be placed.
    """
    # ── 1. Collect votes from all agents ─────────────────────────────────────
    votes: list[AgentVote] = [
        openclaw_vote,
        trend_analyze(symbol, market_snapshot, indicators),
        momentum_analyze(symbol, market_snapshot, indicators),
        mean_reversion_analyze(symbol, market_snapshot, indicators),
    ]

    # ── 2. Compute confidence-based scores ────────────────────────────────────
    scores = {"BUY": 0.0, "SELL": 0.0, "HOLD": 0.0}
    groups = {"BUY": [], "SELL": [], "HOLD": []}

    for v in votes:
        scores[v.signal] += v.confidence
        groups[v.signal].append(v)
        logger.info(
            "  [%s] signal=%-4s confidence=%.0f%% | %s",
            v.agent_name, v.signal, v.confidence * 100, v.reason,
        )

    # Prevent floating point equality bugs (e.g. 0.8 + 0.05 = 0.8500000000000001)
    scores = {k: round(v, 6) for k, v in scores.items()}

    logger.info(
        "Confidence Scores for %s: BUY=%.2f SELL=%.2f HOLD=%.2f",
        symbol, scores["BUY"], scores["SELL"], scores["HOLD"],
    )

    # ── 3. Resolve majority ───────────────────────────────────────────────────
    max_score = max(scores.values())
    winners = [s for s, score in scores.items() if score == max_score]

    # If there is a tie, or the max score < threshold -> HOLD
    if len(winners) > 1:
        logger.info("Consensus tie for %s (max_score=%.2f). Forcing HOLD.", symbol, max_score)
        return TradeRecommendation(
            symbol=symbol.upper(),
            action="HOLD",
            quantity=_HOLD_QUANTITY,
            confidence=0.5,
            reason="Consensus tie.",
        )

    if max_score < MIN_CONSENSUS_SCORE:
        logger.info("Max score %.2f < threshold %.2f. Forcing HOLD for %s.", max_score, MIN_CONSENSUS_SCORE, symbol)
        return TradeRecommendation(
            symbol=symbol.upper(),
            action="HOLD",
            quantity=_HOLD_QUANTITY,
            confidence=0.5,
            reason="Consensus strength below threshold.",
        )

    winning_signal = winners[0]
    winning_group = groups[winning_signal]

    # ── 4. Compute final confidence (sum(c^2) / sum(c)) ───────────────────────
    sum_c2 = sum(v.confidence ** 2 for v in winning_group)
    sum_c = sum(v.confidence for v in winning_group)
    
    final_confidence = sum_c2 / sum_c if sum_c > 0 else 0.5
    final_confidence = round(final_confidence, 6)

    # ── 5. Build Final Recommendation ─────────────────────────────────────────
    action = winning_signal
    quantity = _EXECUTE_QUANTITY if winning_signal in ("BUY", "SELL") else _HOLD_QUANTITY
    combined_reason = " | ".join(f"[{v.agent_name}] {v.reason}" for v in winning_group)

    result = TradeRecommendation(
        symbol=symbol.upper(),
        action=action,
        quantity=quantity,
        confidence=final_confidence,
        reason=combined_reason,
    )

    logger.info(
        "Consensus FINAL → %s | confidence=%.0f%% | %s",
        action if quantity > 0 else f"HOLD ({winning_signal})",
        final_confidence * 100, combined_reason[:100],
    )

    return result
